### ISSUE TITLE
Support Gitlab CI as well

### ISSUE THREAD

**Issue by gforcada** [plone/meta#131]
Not sure how many companies/individuals are using Gitlab, and thus Gitlab CI to run their CI/CD pipelines, but it would be nice to support them as well.

Disclaimer, we at der Freitag use Gitlab 😅 

A simple `.gitlab-ci.yml` could be:

```yml
image: python:3.8-bullseye

stages:
  - qa
  - test

##
# JOBS
##
lint:
  stage: qa
  script:
    - pip install tox
    - tox -e lint
  except:
    - schedules

release-ready:
  stage: qa
  script:
    - pip install tox
    - tox -e release-check
  except:
    - schedules

dependencies:
  stage: qa
  script:
    - pip install tox
    - tox -e dependencies
  except:
    - schedules

circular-dependencies:
  stage: qa
  script:
    - apt-get update
    - apt-get install -y graphviz graphviz-dev
    - pip install tox
    - tox -e circular
  except:
    - schedules

testing:
  stage: test
  script:
    - pip install tox
    - tox -e test
  except:
    - schedules

coverage:
  stage: test
  script:
    - pip install tox
    - tox -e coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  except:
    - schedules
```

Adjusting the `image` for the specific python version would be almost the only thing to do. Probably creating (beyond the scope of `plone/meta`) a docker image that already comes with `tox` installed would be great though.

So, providing a way to override the default `image` would be enough.
