### ISSUE TITLE
Allow excluding files in i18ndude pre-commit check

### ISSUE THREAD

**Issue by gforcada** [plone/meta#133]
At least on `plone.app.layout` would be useful.

On its test suite there is a template file with a string that is not marked for translation. It does not make sense to localize that string, nor add a `i18n:ignore="true"` to it.

The easiest would be to:

```yaml
-   repo: https://github.com/collective/i18ndude
    rev: "6.0.0"
    hooks:
    -   id: i18ndude
        exclude: .*\/tests\/.*.pt
```

This last line would be what we are missing.
