### ISSUE TITLE
Towncrier: Support setting the issue_format

### ISSUE THREAD

**Issue by ericof** [plone/meta#147]
Right now, it is not possible to set `issue_format` for `[tool.towncrier]` in `pyproject.toml`, as the `towncrier_extra_lines` are added after the existing last `[[tool.towncrier.type]]` entry.

I propose we add support for a `towncrier_issue_format` configuration on `.meta.toml`:

```toml
[pyproject]
towncrier_issue_format = "[#{issue}](https://github.com/plonegovbr/plonegovbr.portal/issues/{issue})"
```
