### ISSUE TITLE
Switch to uv?

### ISSUE THREAD

**Issue by gforcada** [plone/meta#246]
It has been on the headlines for quite a while, a fast(er) replacement for `pip`, but not only that.

Should we switch to it on our GHA? 🤔 

I made a test PR on `plone.batching`: https://github.com/plone/plone.batching/pull/83

The changes are mostly to be done here in `plone.meta` and roll them over to the distributions.

❗ **one caveat though**: as soon as we change the workflows in this repo, i.e `.github/workflows/XXX.yml` all repositories that depend on them will (probably 🤔 ) break, so it might be a good idea to first move all repositories to point to a stable version, and then merge this, so we can freely break stuff without breaking repositories 😅 

My idea:

- make a 1.0 release of `plone.meta`
- update all distributions with:

```yml
jobs:
  qa:
    uses: plone/meta/.github/workflows/qa.yml@1.0.0
  test:
    uses: plone/meta/.github/workflows/test.yml@1.0.0
  coverage:
    uses: plone/meta/.github/workflows/coverage.yml@1.0.0
  dependencies:
    uses: plone/meta/.github/workflows/dependencies.yml@1.0.0
  release_ready:
    uses: plone/meta/.github/workflows/release_ready.yml@1.0.0
  circular:
    uses: plone/meta/.github/workflows/circular.yml@1.0.0
```

- we can then start making breaking changes in `plone.meta` 🎉 

@davisagli @mauritsvanrees does it sound sane? 🤔
