### ISSUE TITLE
meta generate a wrong matrix in gitlab-ci file

### ISSUE THREAD

**Issue by 1letter** [plone/meta#260]
i use the current main branch and run plone/meta with no custom settings for the gitlab ci my meta.toml file.

i get the following generate gitlab-vi file
```
testing:
  .....
  parallel:
    matrix:
      - DOCKER_IMAGE: python:3.12-bookworm
        TOX_ENV: py312-plone61
      - DOCKER_IMAGE: python:3.12-bookworm
        TOX_ENV: py312-plone61
 ....
```

here is a double entry?
