### ISSUE TITLE
another linter: rstcheck

### ISSUE THREAD

**Issue by gforcada** [plone/meta#30]
https://pypi.org/project/rstcheck/

I see that plone.rest is starting to use it.

**Comment by mauritsvanrees** [comment]
Alternative would be to use `twine check`.
See https://pypi.org/project/readme-renderer/ which advocates doing this.

**Comment by gforcada** [comment]
If we want to use `rstcheck`:

```yml
-   repo: https://github.com/rstcheck/rstcheck
    rev: "v6.1.2"
    hooks:
    -   id: rstcheck
        additional_dependencies:
          - sphinx
```

`twine check` would only check that the package's README, to be displayed on PyPI is fine, but not all the rst syntax scattered around the package, in docstrings, documentation files, etc...

But having a check to ensure that the `README` is ready to be published to PyPI seems like a great idea!
