### ISSUE TITLE
pyupgrade linter: specify the python version

### ISSUE THREAD

**Issue by ale-rt** [plone/meta#41]
It is possible to pass `args: [--pyN-plus]`, e.g.:
```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
```
