### ISSUE TITLE
Lint: i18ndude check

### ISSUE THREAD

**Issue by gforcada** [plone/meta#60]
Add [`i18ndude`](https://pypi.org/project/i18ndude/) on all repositories to ensure all messages are properly marked for translation 😄

**Comment by gforcada** [comment]
After a few rounds of local testing, seems that once we get https://github.com/collective/i18ndude/pull/106 merged and released we could finally add

```yaml
-   repo: https://github.com/collective/i18ndude
    rev: "fix-pre-commit"
    hooks:
    -   id: i18ndude
```

As another pre-commit hook 🎉
